preprocessing:
  src_point_cloud: D:\GitHubProjects\Terranum_repo\Barmasse_pipeline\data\gridsearch\data\Barmasse_2025_AllScans_Raw_Sub2cm.laz
  tile_size:  100
  overlap: 50
  grid_size: 10
  stripe_width: 20
  stripe_dim: x
  method: invmultiquadric
  method_epsilon: 0.2
  output_type: laz  # choose between las, laz and txt
  do_skip_existing_flatten: False
  skip_to_step: 0
  num_workers: 6
postprocessing:
  src_clean_stripes: default # keep "default" if you didn't saved the clean stripes over the flatten stripes
  src_floor_stripes: default   # keep "default" if you didn't change the location of the floors compiled during preprocessing
  src_original_stripes: default   # keep "default" if you didn't change the location of the floors compiled during preprocessing
  src_resulting_file: default # keep "default" if you want the resulting file to be saved next to "src_point_cloud" of preprocessing
  output_type: laz # keep "default" if you want the resulting file to have the same extension as the input
  skip_to_step: 0
