preprocessing:
  src_point_cloud: D:\GitHubProjects\Terranum_repo\Barmasse_pipeline\demo\data\Barmasse_2025_AllScans_Raw_Sub2cm_aligned_tile_6_8_small.laz
  tile_size:  20
  overlap: 10
  grid_size: 10
  stripe_width: 20
  stripe_dim: x
  method: multiquadric
  method_epsilon: 0.2
  output_type: txt  # choose between las, laz and txt
  output_txt_offset: [2586435, 1098142, 0]
  do_skip_existing_flatten: True
  skip_to_step: 11
postprocessing:
  src_clean_stripes: default # keep "default" if you didn't saved the clean stripes over the flatten stripes
  src_floor_stripes: default   # keep "default" if you didn't change the location of the floors compiled during preprocessing
  src_original_stripes: default   # keep "default" if you didn't change the location of the floors compiled during preprocessing
  src_resulting_file: default # keep "default" if you want the resulting file to be saved next to "src_point_cloud" of preprocessing
  skip_to_step: 0
  output_type: las  # choose between las, laz and txt
  rounding_floor_flatten: 3
  rounding_clean_final: 3
